"""qpubench — modality-agnostic quantum benchmark framework."""
from .backends import AlgorithmAdapter, BackendAdapter, StubGateAdapter, StubMBQCAdapter
from .observability import BenchmarkLogger, JSONFormatter
from .runner import BenchmarkRunner
from .schemas import (
    AdaptIteration,
    AlgorithmSpec,
    BackendSpec,
    BenchmarkRecord,
    CircuitFormat,
    CircuitSpec,
    ComplexNumber,
    ComputingModel,
    ErrorMitigationStrategy,
    ExecutionOptions,
    ExpectationResult,
    FidelityMetric,
    FidelityResult,
    JobStatus,
    MBQCPattern,
    MBQCProgramWord,
    MBQCRound,
    MBQCRoundResult,
    PauliLabel,
    PauliTerm,
    QuantumResult,
    QubitModality,
    ReactionCoordinateSpec,
    ReactionPathResult,
    ShotResult,
    SparsePauliObservable,
    VQAConfig,
    ZNEConfig,
)
from .store import NDJSONStore, ParquetStore, S3Store

__version__ = "0.1.0"

__all__ = [
    "__version__",
    "AdaptIteration",
    "AlgorithmAdapter",
    "AlgorithmSpec",
    "BackendAdapter",
    "BackendSpec",
    "BenchmarkLogger",
    "BenchmarkRecord",
    "BenchmarkRunner",
    "CircuitFormat",
    "CircuitSpec",
    "ComplexNumber",
    "ComputingModel",
    "ErrorMitigationStrategy",
    "ExecutionOptions",
    "ExpectationResult",
    "FidelityMetric",
    "FidelityResult",
    "JSONFormatter",
    "JobStatus",
    "MBQCPattern",
    "MBQCProgramWord",
    "MBQCRound",
    "MBQCRoundResult",
    "NDJSONStore",
    "ParquetStore",
    "PauliLabel",
    "PauliTerm",
    "QuantumResult",
    "QubitModality",
    "ReactionCoordinateSpec",
    "ReactionPathResult",
    "S3Store",
    "ShotResult",
    "SparsePauliObservable",
    "StubGateAdapter",
    "StubMBQCAdapter",
    "VQAConfig",
    "ZNEConfig",
]
